version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/index.html
    networks:
      - mynetwork

volumes:
  nginx:

networks:
  mynetwork:
