# workflow 名稱
name: CI

# 什麼情況下觸發 workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform (pull or rollback)'
        required: true
        default: 'pull'
        options:
          - pull
          - rollback

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Validate HTML
          run: |
            npm install -g htmlhint
            htmlhint index.html

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: check  # 確保在檢查作業成功後執行

    steps:
      # 簽出您的存儲庫
      - name: pull code
        uses: actions/checkout@v2

      # 設置 SSH 金鑰
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          # 添加已知主機
          ssh-keyscan -H 18.182.31.31 >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2 via Bastion Host
        env: 
            GITHUB_EVENT_NAME: ${{ github.event_name }}
            GITHUB_EVENT_INPUTS_ACTION: ${{ github.event.inputs.action }}
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@18.182.31.31 << EOF
          export GITHUB_EVENT_NAME="${{ github.event_name }}"
          export GITHUB_EVENT_INPUTS_ACTION="${{ github.event.inputs.action }}"
          cd ~/cicd-demo
      
          # Echo 出環境變數以進行調試
          echo "GITHUB_EVENT_NAME: \$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_INPUTS_ACTION: \$GITHUB_EVENT_INPUTS_ACTION"
      
          if [ "\$GITHUB_EVENT_NAME" = "push" ]; then
              echo "Pulling latest changes from main..."
              git pull origin main --ff-only
          elif [ "\$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "\$GITHUB_EVENT_INPUTS_ACTION" = "rollback" ]; then
                  echo "Rolling back to specified tag..."
                  git checkout tags/your-tag-name
              else
                  echo "No valid action specified for rollback."
              fi
          fi

          # 信息寫入 status.txt
          echo "Deployment successful on $(date)" >> status.txt

          docker-compose down
          docker-compose up -d --build

          # 繼續進行其他操作
          # yarn build
          # docker-compose pull
          # docker-compose down
          # docker-compose up -d --build
          EOF
