# workflow 名稱
name: CI

# 什麼情況下觸發 workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform (pull or rollback)'
        required: true
        default: 'pull'
        options:
          - pull
          - rollback

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # 簽出您的存儲庫
      - name: pull code
        uses: actions/checkout@v2

      # 設置 SSH 金鑰
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          # 添加已知主機
          ssh-keyscan -H 18.182.31.31 >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2 via Bastion Host
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@18.182.31.31 << 'EOF'
          cd ~/cicd-demo

           if [ "$GITHUB_EVENT_NAME" = "push" ]; then
              # 當 push 到 master 時，執行 git pull
              echo "Pulling latest changes from master..."
              git pull origin main --ff-only
          elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
              # 當手動觸發工作流時的行為
              if [ "$GITHUB_EVENT_INPUTS_ACTION" = "rollback" ]; then
                  echo "Rolling back to specified tag..."
                  git checkout tags/your-tag-name
              else
                  echo "No valid action specified for rollback."
              fi
          fi

          # 信息寫入 status.txt
          echo "Deployment successful on $(date)" >> status.txt

          docker-compose down
          docker-compose up

          # 繼續進行其他操作
          # yarn build
          # docker-compose pull
          # docker-compose down
          # docker-compose up -d --build
          EOF
